# docker-compose.yml
version: '3'

services:
  selenium:
    image: selenium/standalone-firefox
    container_name: 'selenium'
    ports:
    - 4444:4444
    - 5900:5900
    shm_size: '4gb'
    volumes:
      - .:/app
  booster:
    build: .
    container_name: 'booster'
    command: ["python3", "app.py"]
    restart: always
    depends_on:
      - selenium
    environment:
      - YOU_REFERRAL_URL = "https://invite.duolingo.com/BDHTZTB5CWWKS7FOZYMMJYBLCI"
      - COUNTER = 1
    volumes:
      - .:/app
